Additional notes to README.md 3635 Corrected
hackforla/website-wiki pull request #4
Opened 2023-03-20 18:23 UTC by t-will-gillis

Fixes to links, additional cFixes https://github.com/hackforla/website/issues/3635
Fixes [hackforla/website-wiki/pull/2](https://github.com/hackforla/website-wiki/pull/2)

### What changes did you make and why did you make them ?
- Added the missing links noted by @JessicaLucindaCheng 
- Took the opportunity to make other edits, add info and links

2023-03-20 18:27 UTC, JessicaLucindaCheng commented
- Review Availability: 2 hours
- ETA: Tue, March 21, 2023

2023-03-22 01:05 UTC, JessicaLucindaCheng commented on README.md
> +- [Additional CSS](https://squidfunk.github.io/mkdocs-material/customization/#additional-javascript) - using a separate style sheet to adjust specific elements
Is this link supposed to jump to: https://squidfunk.github.io/mkdocs-material/customization/#additional-css? Currently, it goes to https://squidfunk.github.io/mkdocs-material/customization/#additional-javascript

2023-03-22 01:21 UTC, JessicaLucindaCheng commented on README.md
> +  - [Tables](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#tables) – adds ability of create tables in Markdown
Instead replace the `of` with `to`, so the result is `adds ability to create tables in Markdown`

2023-03-22 01:25 UTC, JessicaLucindaCheng requested changes
@t-will-gillis Thanks for making the changes requested in other pr! The additional changes you made on top of that improved the document.

I do have a few more requested changes. See my in-line comments. Thanks.

2023-03-22 01:25 UTC, JessicaLucindaCheng commented on README.md
> +- [Additional CSS](https://squidfunk.github.io/mkdocs-material/customization/#additional-javascript) - using a separate style sheet to adjust specific elements
Is this link supposed to jump to: https://squidfunk.github.io/mkdocs-material/customization/#additional-css? If yes, please fix the link.

2023-03-22 01:25 UTC, JessicaLucindaCheng commented on README.md
> +  - [Tables](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#tables) – adds ability of create tables in Markdown
Replace the `of` with `to`, so the result is `adds ability to create tables in Markdown`

2023-03-22 02:49 UTC, t-will-gillis commented on README.md
> +- [Additional CSS](https://squidfunk.github.io/mkdocs-material/customization/#additional-javascript) - using a separate style sheet to adjust specific elements
Yes! it should, thank you

2023-03-22 02:50 UTC, t-will-gillis commented on README.md
> +  - [Tables](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#tables) – adds ability of create tables in Markdown
Agreed, thank you

2023-03-22 21:55 UTC, JessicaLucindaCheng approved these changes
@t-will-gillis LGTM! Good job!

2023-03-22 21:57 UTC, merged