Refactor Decision Record directory structure and file names
hackforla/website-wiki pull request #8
Opened 2023-05-15 04:25 UTC by vraer

This pull request introduces significant updates to the Decision Record (DR) directory in the `website-wiki` repository. The changes aim to improve the organization and readability of decision records.

**Key Changes:**

1. **New Folder Structure for Decision Records:** A new folder structure has been implemented for the decision records. Two new folders, `adopted` and `not_implemented`, have been created to categorize the decision records based on their implementation status.

2. **Renaming of Files in DR Directory:** The files in the DR directory have been renamed for clarity and consistency. The new naming convention removes the `DR:` prefix, replaces spaces with hyphens, converts the title to lowercase, and makes minor changes to the file name to avoid special characters.

3. **Content Updates:** New content has been added to the `decision-records-management.md` and `index.md` files. These updates provide more context and guidance for managing and navigating the decision records. Specifically, `decision-records-management.md` now houses the necessary templates and instructions for creating new decision records, while `index.md` contains a list of all the decision records grouped by `adopted` and `not_implemented`.

4. **.pages File Addition:** A `.pages` file has been added, utilizing the recently added AwesomePages plugin to organize how the DR directory appears in the wiki's overall navigation.

2023-05-15 20:54 UTC, JessicaLucindaCheng commented
Availability: 2 hours
ETA: Tue, May 16, 2023

2023-05-15 22:02 UTC, JessicaLucindaCheng commented
@vraer In order to review your changes, I need to update my forked main branch locally. However, I am running into these errors I think are caused by having a colon in the file name:
<details>
  <summary>Click here to see screenshot of the error</summary>
  <img width="655" alt="error updating main website-wiki" src="https://github.com/hackforla/website-wiki/assets/31293603/70bc28a1-ecd1-49d5-a5e6-846b9bd99145">
</details>

I'm using Windows 11.

Did you encounter this error when you tried updating your forked website-wiki's main branch locally? If yes, how did you fix the error?

2023-05-16 01:33 UTC, vraer commented
@JessicaLucindaCheng I've removed all the colons from the original DR filenames in the upstream repo's main branch. Syncing your forked main branch _should_ resolve the error. Let me know if you still have trouble!

2023-05-18 00:15 UTC, JessicaLucindaCheng commented
- Review Availability: 2 hours
- Review ETA: Thu, May 17, 2023

2023-05-19 06:52 UTC, JessicaLucindaCheng commented
I'm still having problems pulling the files and viewing the changes. I'm going to work on it tomorrow to see if I can figure out what is going on.

- Review Availability: 2 hours
- Review ETA: Fri, May 18, 2023

2023-05-20 06:22 UTC, JessicaLucindaCheng commented
I finally figured out how to view the changes but it required a work around and may not be how we want junior developers to review changes in prs. In ERs or maybe a discussion or both, which I will write, I think the following needs to happen:
- An issue for instructions for reviewing prs in the website-wiki repo, so we can figure out how we want junior developers to review changes in prs
- Depending on the above, see if anyone else has issues with the colons error that I had, even if after I reforked it and deleted my local and tried pulling it down.
  - If yes, that needs to be fixed. 

I think I will finally be able to review the changes tomorrow. Thank you for your patience while I worked through the problems I was having.
- Review Availability: 2 hours
- Review ETA: Sat, May 19, 2023

2023-05-22 03:39 UTC, JessicaLucindaCheng requested changes
@vraer Thanks for all your hard work on the wiki! I liked the structure and clear instructions for the Decision Records Management page. 

- Since I'm not sure what discussions you have had with Bonnie, if anything I ask you to change contradicts what Bonnie has said, just follow what Bonnie has said. Also, let me know so that I don't ask you to make those changes in the future.
- Also, I wasn't sure if you were supposed to fix problems with links, grammar, spelling, etc, or if that is out of the scope of what you are doing. If any changes I suggested are out of the scope of what you are supposed to be doing right now, let me know and I'll write an ER so that issues can be made to fix them.
- **Edit:** Just spoke with Bonnie and got a better understanding of the scope of what you are doing, which is just to get the website-wiki up and running so it is useable and we can start adding stuff to it again. Thus, any changes that I am requesting outside of that scope, you can just leave a comment, "Out of scope" and leave the requested change unresolved. I'll go through anything unresolved and make sure that eventually there are issue(s) made from it to fix the things. 

In addition to my in-line comments, please do the following as well:
- [ ] In your original PR comment, please add `Fixes https://github.com/hackforla/website/issues/4363` so it links back to the issue since you added the updates to that decision records as part of this pr.
- [ ] For `docs/DR/adopted/use-merge-commit-for-gh-pages-updates.md`, can the title be changed from "Use merge commit for gh pages updates" to "Update feature branches using merge commit"? The reason is the current title might be confused with updating the gh-pages branch when the decision record is actually about updating the feature branches.
- [ ] In the docs/DR/adopted/update-gha-with-dependabot.md, under the Feasibility Determination section, in the paragraph that starts with `Notes:`, change
  ```
  The issue to create the [file](https://github.com/hackforla/website/issues/3843)
  ```
  to
  ```
  Issue [#3843](https://github.com/hackforla/website/issues/3843) creates the file for the website repo.
  ```
- [ ] In `docs/DR/index.md`, I noticed the titles of the decision records are based on the filename with the first letter capitalized but for the Decision Records Management page you manually added each file and had different capitalization. You may want to consider using a `title:` meta-key for each page. For more info on how MkDocs does titles, see [Setting the page title](https://squidfunk.github.io/mkdocs-material/reference/#setting-the-page-title) and ["title" in the "Meta-Data" section](https://www.mkdocs.org/user-guide/writing-your-docs/#meta-data).
  - Pros of doing this are
    - This will allow you to have more control over the capitalization and titles independent of the filename.
    - This will also make the capitalization the same in the navigation on the left side of the website.
  - Cons of doing this are
    - If the wording of the title is different than the filename, the left navigation will list it alphanumerically by its filename and not its title.
- [ ] Can the directory `DR` be renamed to `Decision Records`? Or at least have the directory name be displayed as `Decision Records`? I'm not sure a new team member will know what DR stands for.

2023-05-22 03:39 UTC, JessicaLucindaCheng commented on docs/DR/adopted/standardize-html-img-tag.md
> +Use the img HTML tag without an ending slash meaning <img...> (Source 1).
Put <img...> in backticks otherwise it doesn't show up on the page since it is read as an actual tag. See line 13 in this file for an example of <img...> in backticks.

2023-05-22 03:39 UTC, JessicaLucindaCheng commented on docs/DR/adopted/explore-local-machine-linters.md
> +- If the decision to implement ESLint as the standard local linter were made, we would need to add the files it creates to the main repo; a package.json and .eslintrc.yml config file and we would als
Change the colon in `main repo; a package.json and .eslintrc.yml` to a comma so the result is `main repo, a package.json and .eslintrc.yml`. The punctuation didn't make sense to me with the colon, so I think it is supposed to be a comma.

2023-05-22 03:39 UTC, JessicaLucindaCheng commented on docs/DR/adopted/hide-button-on-toolkit-page.md
>  Using Dockers to check to see if the button has been hidden and the button is still within toolkit.html
Change `Dockers` to `Docker`

2023-05-22 03:39 UTC, JessicaLucindaCheng commented on docs/DR/adopted/link-projects-to-project-pages.md
> +Per comment, it was proposed that a list of "good second issues" be made to add the hyperlinks to each of the projects in the .md files. Before this issue's linked pull request, the project names on
Change `github pages` to `GitHub pages`

2023-05-22 03:39 UTC, JessicaLucindaCheng commented on docs/DR/adopted/use-merge-commit-for-gh-pages-updates.md
> +Over time, feature branches become out of date with the code in the gh-pages branch. After updating the feature branch as outlined in steps [A. Updating a feature branch with changes from gh-pages](h
- [ ] The links in this paragraph need to be updated to link to the MkDocs documentation instead of the old wiki. Though, I'm not sure if you are ready to do this yet or if you plan on doing it later because I don't know what your plan is for changing links pointing to the old wiki to the new wiki.
- [ ] In the last sentence
  > (An "update the feature branch" pull request means a pull request that is opened for updating a feature branch with changes from gh-pages branch.)

  add `the` to `from gh-pages branch` so the result is `from the gh-pages branch`.

2023-05-22 03:39 UTC, JessicaLucindaCheng commented on docs/DR/adopted/use-merge-commit-for-gh-pages-updates.md
> +Merging an "update the feature branch" pull request into the feature branch using **"Create a merge commit"** option. For how to do it, see [D. (TECH LEADS ONLY) Merge the pull request into the featu
The links in this paragraph need to be updated to link to the MkDocs documentation instead of the old wiki. Though, I'm not sure if you are ready to do this yet or if you plan on doing it later because I don't know what your plan is for changing links pointing to the old wiki to the new wiki.

2023-05-22 03:39 UTC, JessicaLucindaCheng commented on docs/DR/adopted/update-gha-with-dependabot.md
> +[#2065](https://github.com/hackforla/website/pull/3414)
The link is confusing. Change it to
```
[#2065](https://github.com/hackforla/website/issues/2065) and its PR [#3414](https://github.com/hackforla/website/pull/3414)
```

2023-05-22 03:39 UTC, JessicaLucindaCheng commented on docs/DR/adopted/update-gha-with-dependabot.md
> +Our GHA are not latest version and hence we need to be notified when dependencies are out-of-date so that they don't break unexpectedly. The issue [#2065](https://github.com/hackforla/website/pull/34
- [ ] Add `Our GHA are not latest version` to `Our GHA are not the latest versions`
- [ ] Change `The issue [#2065](https://github.com/hackforla/website/pull/3414)` to `The issue [#2065](https://github.com/hackforla/website/issues/2065)` because the current link is confusing.

2023-05-22 03:39 UTC, JessicaLucindaCheng commented on docs/DR/adopted/update-gha-with-dependabot.md
>  - As Github Advisory Database powers Dependabot alerts for the impacted GH repository, so no additional action needs to be performed after Dependabot is enabled which has been done .
- [ ] Remove ` so`
- [ ] Remove the extra space before the period.

2023-05-22 03:39 UTC, JessicaLucindaCheng commented on docs/DR/adopted/update-gha-with-dependabot.md
>  - Dependabot alert makes it easier to stay up-to-date and can be managed similar to other PRs ,thus eliminating the need for issue [#2065](https://github.com/hackforla/website/pull/3414).
- [ ] Fix the spacing in `other PRs ,thus` so it becomes `other PRs, thus`
- [ ] Change `issue [#2065](https://github.com/hackforla/website/pull/3414)` to `issue [#2065](https://github.com/hackforla/website/issues/2065)`

2023-05-22 03:39 UTC, JessicaLucindaCheng commented on docs/DR/decision-records-management.md
> +    1. In the `adopted` directory, create a new markdown file for the decision record.
I think this should be more specific, so change
`adopted` directory
to
`docs/DR/adopted` directory

2023-05-22 03:39 UTC, JessicaLucindaCheng commented on docs/DR/decision-records-management.md
> +    1. In the `not_implemented` directory, create a new markdown file for the decision record.
- [ ] Can the actual `not_implemented` directory be named `not-implemented` so we are consistent with how we name directories and files with dashes and not underscores?
- [ ] I think this should be more specific, so change
`not_implemented` directory
to
`docs/DR/not_implemented` directory 
(or if we are changing the directory name then to `docs/DR/not-implemented` directory)

2023-05-22 03:39 UTC, JessicaLucindaCheng commented on docs/DR/decision-records-management.md
> +    2. Name the file using the format `<short-description>.md`, replacing `<short-description>` with a brief description of the decision.
I think there should be an example here similar to  how there is an example in 2 for the Solution Adopted section.

2023-05-22 03:39 UTC, JessicaLucindaCheng commented on docs/DR/not_implemented/receive-project-updates-from-pm.md
> +[#2473](https://github.com/hackforla/website/issues/2473)
To make it easier to read, add `-` to make these bullet points, so the result in Markdown is
```
- [#2450](https://github.com/hackforla/website/issues/2450)
- [#2473](https://github.com/hackforla/website/issues/2473)
```

2023-05-22 03:39 UTC, JessicaLucindaCheng commented on docs/DR/not_implemented/receive-project-updates-from-pm.md
> +This will not help with the confusion that PMs have.  In fact, it may create more.
Add the word `confusion`, so it becomes `it may create more confusion.`

2023-05-22 03:39 UTC, JessicaLucindaCheng commented on docs/DR/not_implemented/implement-logging-system-for-hfla-github-actions.md
>  Creating a Github action to print out certain parts of the Github action logs (Name of action, date run, Name of jobs and the job logs except for the run code) in a text document to maintain a perman
Change each instance of `Github` to `GitHub` and standardize the capitalization in the list of log items, so the result is
```
Creating a GitHub action to print out certain parts of the GitHub action logs (name of action, date run, name of jobs and the job logs except for the run code) in a text document to maintain a permanent record of the GitHub action logs.
```

2023-05-22 03:39 UTC, JessicaLucindaCheng commented on docs/DR/not_implemented/implement-logging-system-for-hfla-github-actions.md
>  Using REST API to download job logs seemed to be the most promising avenue although large amount of data processing would need to be done to remove the Github action code from the logs and get the da
- [ ] Add `a` to `although large amount of data processing` so that it becomes `although a large amount of data processing`
- [ ] Change `Github` to `GitHub`

2023-05-22 03:39 UTC, JessicaLucindaCheng commented on docs/DR/not_implemented/implement-logging-system-for-hfla-github-actions.md
> +It was decided to close this issue due to it requiring a advanced skill set and needing a large amount of time while providing little perceived benefit as a result.
Change `a` to `an` in `a advanced skill set` so the result is `an advanced skill set`

2023-05-22 03:39 UTC, JessicaLucindaCheng commented on docs/DR/not_implemented/maintain-design-system-webpages.md
>  This potential solution is not feasible right now because of the extra work required to maintain and keep the Design System webpages up to date. Factors that lead to this decision:
Change `lead` to `led` in `Factors that lead to this decision:` so the result is `Factors that led to this decision:`

2023-05-22 03:39 UTC, JessicaLucindaCheng commented on docs/DR/not_implemented/prevent-liquid-injection-attacks-in-markdown.md
>  Sanitizing project data by escaping HTML tags in the imported markdown for each project to prevent Liquid Injection attacks.
- [ ] Change `markdown` to uppercase `Markdown`
- [ ] Change `Injection` to lowercase `injection`

2023-05-22 03:39 UTC, JessicaLucindaCheng commented on docs/DR/not_implemented/prevent-liquid-injection-attacks-in-markdown.md
>  Refactoring the project loading code in `assets/js/current-projects.js` to use regular expressions to escape HTML special characters before parsing the YAML into a JSON object rather than using liqui
Capitalize `liquid objects` so the result is `Liquid objects`

2023-05-22 03:39 UTC, JessicaLucindaCheng commented on docs/DR/not_implemented/prevent-liquid-injection-attacks-in-markdown.md
> +It was decided that since some projects use HTML tags in their descriptions (namely line breaks) and since any malicious code added to a project's markdown file would have to be added by someone with
Capitalize `markdown file` so the result is `Markdown file`

2023-05-22 03:39 UTC, JessicaLucindaCheng commented on docs/DR/not_implemented/fix-pr-github-actions-bug-with-labels-and-instructions.md
>  To squash the bug that is causing some PRs to not trigger the GitHub Actions(GHA) workflows for PR Labels and Instructions. Specifically for [#2918](https://github.com/hackforla/website/pull/2918) an
Fix spacing and change words to lowercase that don't need capitalization by changing
```
GitHub Actions(GHA) workflows for PR Labels and Instructions.
```
to
```
GitHub Actions (GHA) workflows for PR labels and instructions.
```

2023-05-22 03:39 UTC, JessicaLucindaCheng commented on docs/DR/not_implemented/fix-pr-github-actions-bug-with-labels-and-instructions.md
>    - the steps that I used were: create new branch_1, make commits. create branch_2 from branch_1 (so that those edits are now in branch_2), make commits. make branch_1 PR, merge and squash. create br
- [ ] For lines 25-35
  - [ ] The indentations need to be fixed to match the old wiki page: https://github.com/hackforla/website/wiki/DR:-Squashing-PR-GitHub-Actions-bug,-not-adding-labels-or-instructions.
  
    <details><summary>Click here to see a screenshot of what the bullet points currently look like on the website</summary>
      <img width="352" alt="" src="https://github.com/hackforla/website-wiki/assets/31293603/8c200641-def7-4bce-a26d-499a918d530b">
    </details>
  
  - [ ] Also, make the first word in each bullet point start capitalized. For example, `merge conflict (any on: pull_request workflows will not be triggered)` will become `Merge conflict (any on: pull_request workflows will not be triggered)`

- [ ] For line 35, change the capitalization to sentence case and into bullet points to make it easier to read, so the result should be
```
- The steps that I used were: 
  - Create new branch_1 and make commits.
  - Create branch_2 from branch_1 (so that those edits are now in branch_2) and make commits.
  - Make branch_1 PR, then merge and squash.
  - Create branch_2 PR (there should be 2 commits).
```

2023-05-22 03:39 UTC, JessicaLucindaCheng commented on docs/DR/not_implemented/fix-pr-github-actions-bug-with-labels-and-instructions.md
>    - not merging into the specified branches (this can be found in the workflows .yml file)
Change `workflows .yml file` to `workflows' .yml files`

2023-05-22 03:39 UTC, JessicaLucindaCheng commented on docs/DR/not_implemented/fix-pr-github-actions-bug-with-labels-and-instructions.md
>  </details>
The following requested changes are to 1) clarify what each of the figures show and 2) fix the images so they show correctly on the website.

- [ ] In lines 43-45, change the code to
  ```
  <details><summary>Figure 1: Code snippet of the branches the Set PR Labels workflow will work on</summary>
  
  <img src="https://user-images.githubusercontent.com/31293603/199852407-56a82546-7a13-47ca-9253-b68fe618c487.png" alt="">
  ```
- [ ] In lines 47-49, change the code
  ```
  <details><summary>Figure 2: Where to change your default branch in your repo</summary>
  
  <img src="https://user-images.githubusercontent.com/86996158/179142211-04764947-c20a-4187-898a-d911d6f196f4.png" alt="">
  ```

2023-05-22 03:39 UTC, JessicaLucindaCheng commented on docs/DR/not_implemented/convert-docs-to-markdown-with-existing-add-on.md
> +[Guides Issue #10 Comment](https://github.com/hackforla/guides/issues/10#issuecomment-1066190743)
Make these into bullet points to make it easier to read, so the result is
```
- [#2978](https://github.com/hackforla/website/issues/2978)
- [Guides Issue #10 Comment](https://github.com/hackforla/guides/issues/10#issuecomment-1066190743)
```

2023-05-22 03:39 UTC, JessicaLucindaCheng commented on docs/DR/not_implemented/convert-docs-to-markdown-with-existing-add-on.md
>  ![Screenshot 2022-03-12 174359](https://user-images.githubusercontent.com/38295612/158070915-a6937dde-5b84-46cc-b697-225b2b14021b.png)
For the image to display, change this to use an img HTML tag, so the result is
```
<img src="https://user-images.githubusercontent.com/38295612/158070915-a6937dde-5b84-46cc-b697-225b2b14021b.png" alt="">
```

2023-05-22 03:39 UTC, JessicaLucindaCheng commented on docs/DR/not_implemented/convert-docs-to-markdown-with-existing-add-on.md
>  ![wrong-order](https://user-images.githubusercontent.com/38295612/158072457-1fd97035-a67c-41a3-a221-780b91fa8edf.png)
The images need to be put in img HTML tags so the images display properly. The "Expected Output" and "Actual Output" needs to be formatted so it isn't inline with the images. You could do the following but feel free to change the formatting if you want:
```
  <b>Expected Output</b><br>
  <img src="https://user-images.githubusercontent.com/38295612/158072463-0497a1f4-88e7-4fe5-a22f-80eeed20f60c.png" alt="">
  <br><br>
  
  <b>Actual Output</b><br>
  <img src="https://user-images.githubusercontent.com/38295612/158072457-1fd97035-a67c-41a3-a221-780b91fa8edf.png" alt="">
```

2023-05-22 03:39 UTC, JessicaLucindaCheng requested changes
@vraer Thanks for all your hard work on the wiki! I liked the structure and clear instructions for the Decision Records Management page. 

- Since I'm not sure what discussions you have had with Bonnie, if anything I ask you to change contradicts what Bonnie has said, just follow what Bonnie has said. Also, let me know so that I don't ask you to make those changes in the future.
- Also, I wasn't sure if you were supposed to fix problems with links, grammar, spelling, etc, or if that is out of the scope of what you are doing. If any changes I suggested are out of the scope of what you are supposed to be doing right now, let me know and I'll write an ER so that issues can be made to fix them.

In addition to my in-line comments, please do the following as well:
- [ ] In your original PR comment, please add `Fixes https://github.com/hackforla/website/issues/4363` so it links back to the issue since you added the updates to that decision records as part of this pr.
- [ ] For `docs/DR/adopted/use-merge-commit-for-gh-pages-updates.md`, can the title be changed from "Use merge commit for gh pages updates" to "Update feature branches using merge commit"? The reason is the current title might be confused with updating the gh-pages branch when the decision record is actually about updating the feature branches.
- [ ] In the docs/DR/adopted/update-gha-with-dependabot.md, under the Feasibility Determination section, in the paragraph that starts with `Notes:`, change
  ```
  The issue to create the [file](https://github.com/hackforla/website/issues/3843)
  ```
  to
  ```
  Issue [#3843](https://github.com/hackforla/website/issues/3843) creates the file for the website repo.
  ```
- [ ] In `docs/DR/index.md`, I noticed the titles of the decision records are based on the filename with the first letter capitalized but for the Decision Records Management page you manually added each file and had different capitalization. You may want to consider using a `title:` meta-key for each page. For more info on how MkDocs does titles, see [Setting the page title](https://squidfunk.github.io/mkdocs-material/reference/#setting-the-page-title) and ["title" in the "Meta-Data" section](https://www.mkdocs.org/user-guide/writing-your-docs/#meta-data).
  - Pros of doing this are
    - This will allow you to have more control over the capitalization and titles independent of the filename.
    - This will also make the capitalization the same in the navigation on the left side of the website.
  - Cons of doing this are
    - If the wording of the title is different than the filename, the left navigation will list it alphanumerically by its filename and not its title.
- [ ] Can the directory `DR` be renamed to `Decision Records`? Or at least have the directory name be displayed as `Decision Records`? I'm not sure a new team member will know what DR stands for.

2023-05-28 09:24 UTC, JessicaLucindaCheng approved these changes
@vraer I'm going to go ahead and approve this pr because
1) the changes requested can be made later and
2) I don't want to hold up the progress on the website-wiki since Bonnie wants the website-wiki ready as soon as possible for new submission or edits by other team members.

Thanks for all your hard work on this wiki migration!

2023-05-28 09:25 UTC, merged

2023-07-06 17:57 UTC, vraer commented
@JessicaLucindaCheng FYI, I implemented all of your suggestions in my latest updates to the decision records. Could use some guidance on how to best group all of these commits/PR(s) Let me know if you're up for that discussion :)